// @generated automatically by Diesel CLI.
// This file is generated by `diesel migration run`
// Run migrations to update this file

diesel::table! {
    users (id) {
        id -> Int8,
        #[max_length = 255]
        email -> Varchar,
        #[max_length = 255]
        password_hash -> Varchar,
        #[max_length = 255]
        name -> Varchar,
        is_active -> Bool,
        created_at -> Timestamptz,
        updated_at -> Timestamptz,
    }
}
